version: '3.8'

services:
  web:
    build: .
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; alembic upgrade head; uvicorn main:app --host 0.0.0.0'
    volumes:
      - .:/app
    ports:
      - "80:8000"
    environment:
      - DATABASE_URL_ASYNC=postgresql+asyncpg://seva:mypassword@db:5432/fastapi_db
      - DATABASE_URL_SYNC=postgresql://seva:mypassword@db:5432/fastapi_db
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=seva
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=fastapi_db
volumes:
  postgres_data: